setup = ".muse/setup.sh"
customTools = ["https://raw.githubusercontent.com/amy-keibler/lift-local-tests/failing_tool/.lift/failing_tool.py", "https://raw.githubusercontent.com/gvazquezmorean/lift-local-test/v3-tool/.lift/x.sh"]
